### ISSUE TITLE
Coverage reports for unit tests are empty

### ISSUE THREAD

**Issue by rhutzel** [gonzofish/angular-library-set#10]

**Comment by gonzofish** [comment]
Yeah, I haven't made the effort to do coverage reports yet, but I'll see if I can get to it this weekend.

**Comment by gonzofish** [comment]
Merged in changes to get coverage working. Works on `autoWatch`ed testing as well. The coverage files will save to a `coverage` directory using HTML & lcov output. The lcov file is `lcov.info`, the rest of the files in the `coverage` directory support the HTML output.

For existing projects consult the above commits for changes. But here are the highlights:

- `karma.conf.js`
    - `require('karma-remap-istanbul')` replaced with `require('karma-coverage-istanbul-reporter')`
    - `remapIstanbulReporter` replaced with configuration for `coverageIstanbulReporter`
    - In `reporters` list, `karma-remap-istanbul` replaced by `coverage-istanbul`
- `package.json`
   - Pointing `angular-library-set` to the GitHub project for now @HEAD
   - Removed/uninstalled `karma-remap-istanbul` and `sourcemap-istanbul-instrumenter-loader`
   - Added/installed `istanbul-instrumenter-loader` and `karma-coverage-istanbul-reporter`
- Added `tsconfig.test.json` as the TypeScript configuration for tests
- `webpack.test.js` loaders were updated to:
    - Point to `tsconfig.test.json` as the TypeScript configuration
    - Utilize the `istanbul-insrumenter-loader`
