### ISSUE TITLE
Source maps not working for tests

### ISSUE THREAD

**Issue by litzebauer** [gonzofish/angular-library-set#14]
See this in the Jamsine console: SourceMap position not found for trace: undefined

Sourcemaps aren't working in chrome either

**Comment by gonzofish** [comment]
it should be fixed in master, but i'll take a look at the version you're running (0.0.10-alpha)

**Comment by gonzofish** [comment]
I think this is a result of angular2-template-loader, via [this issue](https://github.com/TheLarkInn/angular2-template-loader/issues/50)

**Comment by gonzofish** [comment]
angular2-template-loader is the culprit. To fix from a shell do:

```shell
npm rm angular2-template-loader
```
Update `package.json` so `angular2-template-loader` is `"0.6.0"` not `"^0.6.0"` and run

```shell
npm i angular2-template-loader
```
