### ISSUE TITLE
Saves the answers to component, pipe, etc questions

### ISSUE THREAD

**Issue by litzebauer** [gonzofish/angular-library-set#18]
The answers to questions for component, pipe, etc should not be saved.

**Comment by gonzofish** [comment]
Yeah, I just noticed this myself. We need to make it so that .erector is updated only for init.

**Comment by litzebauer** [comment]
@gonzofish  This isn't resolved yet.  Need to publish new version of erector-set and then I can update the dependency and pass true into inquire function when calling during initial

**Comment by gonzofish** [comment]
Didn't mean to close it...reopened
