### ISSUE TITLE
Can't publish using tagVersion(np)

### ISSUE THREAD

**Issue by litzebauer** [gonzofish/angular-library-set#20]
When trying to tag a version, "np" runs "npm test" to execute the tests.  In angular-library-set "npm test" runs the tests and then stays open watching for changes.  This prevents NP from moving beyond the test phase.  @gonzofish Not sure how you want to handle this.

**Comment by litzebauer** [comment]
A short term workaround is
`npm run tagVersion -- --yolo` 

This skips running the tests before publishing.

**Comment by gonzofish** [comment]
In order to conform to `np` we can switch the `test` script to default to a single tests and have an option to run all tests via `npm test all`.

**Comment by litzebauer** [comment]
ok, sounds good

**Comment by gonzofish** [comment]
Verified working on a local test project
