### ISSUE TITLE
Auto-generate first component

### ISSUE THREAD

**Issue by gonzofish** [gonzofish/angular-library-set#3]
When a library is initialized, it should create the first component. There is a high likelihood that the first component is going to be the same name as the library.

Perhaps the project initialization needs an option to say "don't generate first component", too, to avoid this behavior.

**Comment by litzebauer** [comment]
Up to you on this feature but is it really necessary? I created a project today that had 0 components. Is it a big burden to run the command to create a component after project generation?

**Comment by gonzofish** [comment]
Good point. This could be a CLI argument in the futures; `npm run g i --generate-first-component` or something if the user wants it
