### ISSUE TITLE
bug in manual

### ISSUE THREAD

**Issue by stevermeister** [gonzofish/angular-library-set#32]
`npm i -D angular-librarian`  -  it's not global installation

    `ngl i`  - expected to be global

**Comment by gonzofish** [comment]
In the README, under [To Use the ngl Command](https://github.com/gonzofish/angular-library-set#to-use-the-ngl-command) it talks about how `ngl` isn't a global command by default.

Was there something else missed? I want to ensure the documentation is clear.

**Comment by stevermeister** [comment]
maybe it's good to add reference to this explanation from here:
![screen shot 2017-05-03 at 13 11 14](https://cloud.githubusercontent.com/assets/1526680/25658231/2171ab06-3002-11e7-96cf-c1300e68a687.png)

I wanted to check whether it works and immediately run these two commands without reading details. (yes, know my bad, but I think most developers do so)

**Comment by gonzofish** [comment]
Added docs in 324e740
