### ISSUE TITLE
i18n does not output anything

### ISSUE THREAD

**Issue by tommueller** [gonzofish/angular-library-set#35]
Is it not possible to use angulars i18n tools because this is not an angular-cli application? When I run the code `./node_modules/.bin/ng-xi18n` to extract the strings I do not get any error, but no messages.xlf is output as well. 

If so, is there any alternative?

**Comment by gonzofish** [comment]
Currently i18n isn't something I have any experience with, so I'm not sure what the issue may be or any alternative. If you would like to add support for it, feel free to submit a pull request.

**Comment by tommueller** [comment]
Having thought about this, I think this is actually not really implementable ...
angulars i18n support, generates several hard-compiled versions of the code, which is not usable within a library.

I will close this thinking that the code using the component should handover the correctly translated strings, even though for some things this is maybe not the best way.
